BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE USERS_ORA (
        USER_ID NUMBER PRIMARY KEY,
        UNAME VARCHAR2(100),
        FNAME VARCHAR2(100),
        LNAME VARCHAR2(100)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/

INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (1, 'ora_user1', 'Alex', 'Anderson');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (2, 'ora_user2', 'Blake', 'Brown');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (3, 'ora_user3', 'Casey', 'Clark');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (4, 'ora_user4', 'Dakota', 'Davis');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (5, 'ora_user5', 'Eden', 'Evans');
COMMIT;
