BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE USERS_ORA (
        USER_ID NUMBER PRIMARY KEY,
        UNAME VARCHAR2(100),
        FNAME VARCHAR2(100),
        LNAME VARCHAR2(100)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/

INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (1, 'ora_user1', 'Alex', 'Anderson');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (2, 'ora_user2', 'Blake', 'Brown');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (3, 'ora_user3', 'Casey', 'Clark');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (4, 'ora_user4', 'Dakota', 'Davis');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (5, 'ora_user5', 'Eden', 'Evans');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (6, 'ora_user6', 'Finley', 'Foster');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (7, 'ora_user7', 'Gray', 'Green');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (8, 'ora_user8', 'Harper', 'Harris');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (9, 'ora_user9', 'Indigo', 'Irwin');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (10, 'ora_user10', 'Jordan', 'Jones');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (11, 'ora_user11', 'Kai', 'King');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (12, 'ora_user12', 'Logan', 'Lee');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (13, 'ora_user13', 'Morgan', 'Moore');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (14, 'ora_user14', 'Nova', 'Nelson');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (15, 'ora_user15', 'Ocean', 'Owens');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (16, 'ora_user16', 'Parker', 'Parker');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (17, 'ora_user17', 'Quinn', 'Quinn');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (18, 'ora_user18', 'River', 'Roberts');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (19, 'ora_user19', 'Sage', 'Smith');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (20, 'ora_user20', 'Taylor', 'Taylor');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (21, 'ora_user21', 'Valley', 'Vance');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (22, 'ora_user22', 'Willow', 'White');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (23, 'ora_user23', 'Xander', 'Xu');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (24, 'ora_user24', 'Yael', 'Young');
INSERT INTO USERS_ORA (USER_ID, UNAME, FNAME, LNAME) VALUES (25, 'ora_user25', 'Zion', 'Zimmerman');
COMMIT;
